[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/api/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/.netlify/functions/api/robots.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "@neondatabase/serverless", "ws", "dotenv", "cookie-parser", "openai", "jsonwebtoken", "csv-writer", "lightningcss"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"